runmode: debug
addr: :8888
name: apiserver
url: http://0.0.0.0:8888
max_ping_count: 10
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/ginweb.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 2048
  log_backup_count: 7